backend:
  name: github
  repo: cbsalt/personal-blog
  branch: master
  site_domain: https://blogdabia.netlify.app/

media_folder: static/assets/img
public_folder: /assets/img
publish_mode: editorial_workflow
slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: posts # Used in routes, e.g. /admin/collections/blog
    label: posts # Used in the UI
    folder: posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: 'Post Image', name: 'image', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Introduction', name: 'introduction', widget: 'string' }
      - {
          label: 'Main Class',
          name: 'main-class',
          widget: 'select',
          options: ['jekyll', 'css', 'js', 'html', 'svg', 'dev', 'misc'],
        }
      - {
          label: 'Color',
          name: 'color',
          widget: 'select',
          options:
            [
              { label: 'Fashion', value: '#B31917' },
              { label: 'Branding', value: '#2DA0C3' },
              { label: 'Marketing', value: '#D6BA32' },
              { label: 'Travels', value: '#EB7728' },
            ],
        }
      - { label: 'Tags', name: 'tags', widget: 'list', default: [''] }
      - {
          label: 'Category',
          name: 'categories',
          widget: 'list',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }